[package]
name = "sudokusolver"
version = "0.2.0"
authors = ["Anders J. Andersen <andersj.andersen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^0.8.1"
